version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

  # Go API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_api
    environment:
      ENVIRONMENT: development
      PORT: 8080
      DATABASE_URL: postgres://postgres:password@postgres:5432/todo_db?sslmode=disable
      JWT_SECRET: your-secret-key-change-this-in-production
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - todo_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  todo_network:
    driver: bridge 