# Development Environment
# Usage: docker-compose up
# 
# For production: docker-compose -f docker-compose.prod.yml up

services:
  postgres:
    image: postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-todo_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_api
    env_file:
      - .env
    environment:
      # Override database URL to point to postgres service
      DATABASE_URL: postgres://${DB_USER:-postgres}:${DB_PASSWORD:-password}@postgres:5432/${DB_NAME:-todo_db}?sslmode=disable
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - postgres
    networks:
      - todo_network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./secrets:/etc/secrets:ro

volumes:
  postgres_data:

networks:
  todo_network:
    driver: bridge 