# Production Environment - uses environment variables only
# Usage: 
#   export DATABASE_URL="postgres://..."
#   export JWT_SECRET="..."
#   docker-compose -f docker-compose.prod.yml up

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  api:
    build:
      context: .
      dockerfile: Dockerfile
    # NO env_file in production - all vars come from environment
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-production}
      PORT: ${PORT:-8080}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      
      # Apple OAuth (if used)
      APPLE_TEAM_ID: ${APPLE_TEAM_ID:-}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID:-}
      APPLE_KEY_ID: ${APPLE_KEY_ID:-}
      APPLE_KEY_PATH: ${APPLE_KEY_PATH:-}
      APPLE_REDIRECT_URL: ${APPLE_REDIRECT_URL:-}
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - postgres
    networks:
      - todo_network
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./secrets:/etc/secrets:ro

volumes:
  postgres_data:

networks:
  todo_network:
    driver: bridge 